name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest pytest-cov radon xenon; fi

      - name: Run unit tests with coverage
        env:
          PYTHONPATH: shared
        run: |
          pytest -q shared/tests/unit \
            --cov=core.base \
            --cov=core.config \
            --cov=core.utils.architectural_pattern_detector \
            --cov=core.utils.tech_stack_detector \
            --cov-report=term-missing \
            --cov-fail-under=85

      - name: Ruff lint
        run: |
          ruff check .

      - name: Mypy type check
        env:
          PYTHONPATH: shared
        run: |
          mypy --config-file mypy.ini

      - name: Complexity gate (xenon)
        run: |
          xenon --max-absolute B --max-modules A --max-average A shared
